In [1]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('tetrahymena_padel_withDep.csv')
dataf1 = dataset.drop(['Name'], axis = 1)

dataf1.shape

(1995, 1442)

In [2]:
dataset_rmNA = dataf1.dropna(axis = 'columns', how = 'any')

dataset_rmNA.shape

(1995, 1342)

In [3]:
from sklearn.feature_selection import VarianceThreshold

threshold_n=0.90
sel = VarianceThreshold(threshold=(threshold_n* (1 - threshold_n) ))
sel_var=sel.fit_transform(dataset_rmNA)
dataset_VT = dataset_rmNA[dataset_rmNA.columns[sel.get_support(indices=True)]]

In [4]:
dataset_VT_rmDep = dataset_VT.drop(['Dependent'], axis = 1)

corrWithDep = dataset_VT.corr().abs().iloc[0]
corrWithVar = dataset_VT_rmDep.corr().abs()

In [5]:
col_corr = set()

for i in range(len(corrWithVar.columns)):
    for j in range(i):
        if (corrWithVar.iloc[i, j] >= 0.9) and (corrWithVar.columns[i] or corrWithVar.columns[j] not in col_corr):
            if (corrWithDep.iloc[i] >= corrWithDep.iloc[j]):
                colname = corrWithVar.columns[j]
                col_corr.add(colname)
            else:
                colname = corrWithVar.columns[i]
                col_corr.add(colname)

In [6]:
dataset_PW = dataset_VT.drop(col_corr, axis = 1)

In [7]:
dataset_cleaned = pd.concat([dataset['Name'], dataset_PW], axis = 1)

In [8]:
dataset_cleaned

,Name,Dependent,apol,nH,nN,nX,ATS0m,ATS2m,ATS3m,ATS4m,...,GGI2,GGI3,VE3_D,VR1_D,TopoPSA,SRW5,AMW,WTPT-3,WTPT-4,XLogP
0,AUTOGEN_tetrahymena_smiles_1,-0.16,10.480000,0,0,4,5171.074121,7540.215000,0.000000,0.000000,...,0.000000,0.0000,-18.368400,4.000000e+06,0.00,0.0,30.375082,9.000000,0.000000,2.864
1,AUTOGEN_tetrahymena_smiles_2,1.64,8.847586,2,1,1,7239.077516,1949.851947,2621.276160,0.000000,...,0.444444,0.0000,-1.399999,1.237595e+01,43.14,0.0,19.846699,9.806844,4.626105,0.927
2,AUTOGEN_tetrahymena_smiles_3,-2.72,5.229172,4,0,0,404.296378,63.536256,3.048192,0.000000,...,0.000000,0.0000,0.000000,1.414214e+00,20.23,0.0,5.337702,2.000000,2.000000,-0.499
3,AUTOGEN_tetrahymena_smiles_4,-0.87,7.429172,4,2,0,796.688476,478.062438,281.606409,34.286112,...,0.222222,0.0000,0.000000,8.452347e+00,55.12,0.0,7.504045,7.181981,2.310660,-1.524
4,AUTOGEN_tetrahymena_smiles_5,-1.32,9.527172,4,2,0,1568.564075,1144.785369,185.742144,4.064256,...,0.000000,0.0000,-14.694720,3.000000e+06,84.13,0.0,9.501190,6.732051,0.000000,-0.801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990,AUTOGEN_tetrahymena_smiles_1991,2.11,41.817102,14,0,0,2866.947075,4462.086500,4797.060613,4455.513126,...,2.000000,1.3125,-65.425009,5.000077e+06,20.23,0.0,7.457711,2.598343,2.598343,8.082
1991,AUTOGEN_tetrahymena_smiles_1992,0.77,46.113895,15,0,0,3827.337071,6201.406280,6977.420328,6354.575813,...,2.666667,2.0625,-72.087307,4.000103e+06,26.88,0.0,7.945316,6.354067,2.618022,6.927
1992,AUTOGEN_tetrahymena_smiles_1993,1.81,48.519895,15,0,0,4595.241074,6764.836324,6885.159416,7178.281617,...,1.333333,1.6875,-81.035263,4.000126e+06,54.57,0.0,8.580810,15.561820,11.883138,6.939
1993,AUTOGEN_tetrahymena_smiles_1994,0.36,52.485790,30,0,0,2883.204099,5127.112152,5765.532231,5794.768395,...,3.777778,2.5000,-5.587272,1.179130e+02,20.23,0.0,5.351626,2.552206,2.552206,7.640
1994,AUTOGEN_tetrahymena_smiles_1995,1.70,46.253516,12,0,0,4289.019073,6980.407137,8091.509670,7617.126824,...,3.555556,2.3750,-87.580131,2.000151e+06,74.60,0.0,9.082794,16.515226,16.515226,5.473